name: Export Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save Image
        run: |
          docker pull --platform linux/amd64 onlyoffice/documentserver:latest
          docker save onlyoffice/documentserver:latest | gzip > onlyoffice.tar.gz

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: onlyoffice-image
          path: onlyoffice.tar.gz
