name: Push to Aliyun ACR

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Aliyun ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Pull and Push Image
        run: |
          docker pull --platform linux/amd64 onlyoffice/documentserver:latest
          docker tag onlyoffice/documentserver:latest ${{ secrets.ALIYUN_REGISTRY }}/m60333/onlyoffice-ds:latest
          docker push ${{ secrets.ALIYUN_REGISTRY }}/m60333/onlyoffice-ds:latest
